version: '3.8'

services:
  aggregator-service:
    build:
      context: ./aggregator-service
    ports:
      - "8081:8080"
    container_name: aggregator-service

  greeting-service:
    build:
      context: ./greeting-service
    ports:
      - "8082:8080"
    container_name: greeting-service

  user-service:
    build:
      context: ./user-service
    ports:
      - "8083:8080"
    container_name: user-service