name: CI pipeline with selfhosted runner
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Show Java and Maven Version
      run: |
        java -version
        mvn -v

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-${{ runner.os }}-

    - name: Build and Test
      run: mvn clean compile test
